apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: wazuh-storage
# Use rancher local-path to provide PersistentVoulume support
provisioner: rancher.io/local-path # This is the provisioner ID
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete

